### ISSUE TITLE
Rename TCK bundle extract & LICENSE file

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/debugging-support-for-other-languages-tck#17]
1. The EFTL TCK has the license name as LICENSE_EFTL.md . This should appear as LICENSE.md in the EFTL bundle with EFTL license in it.

2. The TCK bundle extract folder is named debugging-tck-2.0.0 (with the version appended). This should appear as debugging-tck (without the version) .

**Comment by RohitKumarJain** [comment]
Addressed this issue under PR: https://github.com/eclipse-ee4j/debugging-support-for-other-languages-tck/pull/18
